name: GitHub Actions Check
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  tests:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
